package com.yi.jpshop.entity;

import com.yi.jpshop.entity.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu().dao();
}
